### ISSUE TITLE
npm install fails on windows

### ISSUE THREAD

**Issue by s-a** [richardbutler/node-spritesheet#12]
npm ERR! node-spritesheet@0.3.0 install: `./scripts/imagemagick.sh`
npm ERR! `cmd "/c" "./scripts/imagemagick.sh"` failed with 1

I suggest to remove automatic imagemagick setup and describe it as depedency in your manuals.

Best regards.

**Comment by johnrobertfitz** [comment]
Was able to get this to install/run on windows by:
1. Forking & removing the install script from package.json.
2. Installing imagemagick cli tools on windows.
3. After it saves the css, replace the backslashes in the css sprite path to forward slashes.

Haven't tested extensively with retina images, but otherwise it's working for my simple use case.

**Comment by s-a** [comment]
I did this 3 month ago, but switched to GLUE commandline tool which is more usable with windows. And its crossplatform. Thanks.
